gui:
  showRandomTip: false
  showCommandLog: false
  showBottomLine: true
  showFileIcons: true
  nerdFontsVersion: "3"
  language: "auto"
  theme:
    activeBorderColor:
      - cyan
      - bold
    inactiveBorderColor:
      - default
    optionsTextColor:
      - blue
    selectedLineBgColor:
      - default
    selectedRangeBgColor:
      - reverse
  filterMode: substring
  timeFormat: "2006-01-02 15:04"

git:
  autoFetch: true
  autoRefresh: true
  autoForwardBranches: onlyMainBranches
  parseEmoji: true

  log:
    order: topo-order
    showGraph: always
    showWholeGraph: false

  commit:
    signOff: false
    autoWrapCommitMessage: true
  merging:
    manualCommit: false
  paging:
    colorArg: always
    pager: ""
  branchLogCmd: "git log --color=always --graph --decorate --oneline {{branchName}} --"

os:
  edit: "$EDITOR {{filename}}"
  editAtLine: "$EDITOR +{{line}} {{filename}}"
  editAtLineAndWait: ""
  editInTerminal: true
  openDirInEditor: "$EDITOR {{dir}}"

# Skip prompt asking to create a new repo
notARepository: skip

confirmOnQuit: false
quitOnTopLevelReturn: false
disableStartupPopups: true
promptToReturnFromSubprocess: true
