style = "auto"            # visually better than compact
inline_height = 30        # TUI lines
enter_accept = false

filter_mode = "host"       # only search locally
search_mode = "fuzzy"      # alternative: "prefix"
db_prune = true            # keep DB lean over time

# Privacy / noise
min_duration = 100         # in ms; ignore super-fast commands
ignore_commands = ["ls", "pwd"]
